version: '3'

services:

  app:
    container_name: spring-app
    image: app
    restart: always # recommended way (instead of depends_on)
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - "3307:3306" # external:internal
    environment:
      MYSQL_DATABASE: spring_rest_db
      MYSQL_ROOT_PASSWORD: root


