version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_rest_db
      - MYSQL_PORT=3307
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
    container_name: spring_rest_app
    links:
      - db
    ports:
      - "8080:8080"


