version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_rest_db

  app:
    build: .
    depends_on:
      db:
        condition: service_started
    container_name: spring_rest_app
    links:
      - db
    ports:
      - "8080:8080"


